# Read:
#   https://docs.traefik.io/user-guide/docker-and-lets-encrypt/
#
# first steps:
# touch /opt/traefik/docker-compose.yml
# -- this important, but just ahs to be done for the very first time.
# touch /opt/traefik/acme.json && chmod 600 /opt/traefik/acme.json
# touch /opt/traefik/traefik.toml
#
#
debug = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "build.XXXXXXXXXXX.XXX"
watch = true
exposedbydefault = true

[acme]
email = "technical-accounts@funkedigital.de"
storage = "acme.json"
dnsProvider = "route53"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "route53" # DNS Provider name (cloudflare, OVH, gandi...)
  delayBeforeCheck = 0

# OnHostRule = true
[[acme.domains]]
main = "build.XXXXXXXXXXX.XXX"
sans = ["build.XXXXXXXXXXX.XXX", "artifactory.XXXXXXXXXXX.XXX", "vault.XXXXXXXXXXX.XXX"]
